## Code Book

### Study Design
This study used raw data obtained from the "Human Activity Recognition using Smartphones Dataset". This data measures linear acceleration and angular velocity of 30 participants performing 6 tasks (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING). The measurements were captured using the embedded gyroscope and accelerometer in Samsung smartphones that the participants wore.

This study limits the raw data to only the measures of mean and standard deviation, and then takes the average of these measures for each subject and activity combination.

### Included Variables
#### Identifiers
* subject_num -- identifies the test subject  
* activity_name -- identifies the activity that the subject is performing. The activities are:
    + WALKING
    + WALKING_UPSTAIRS
    + WALKING_DOWNSTAIRS
    + SITTING
    + STANDING
    + LAYING
    
#### Measurements
* tBodyAcc-XYZ      -- body acceleration
* tGravityAcc-XYZ   -- gravity acceleration
* tBodyAccJerk-XYZ  -- linear acceleration
* tBodyGyro-XYZ     -- gyroscope acceleration
* tBodyGyroJerk-XYZ -- angular velocity
* tBodyAccMag       -- magnitude of the body acceleration
* tGravityAccMag    -- magnitude of the gravity acceleration
* tBodyAccJerkMag   -- magnitured of the linear acceleration
* tBodyGyroMag      -- magnitude of the gryoscope acceleration
* tBodyGyroJerkMag  -- magnitude of the angular velocity

For each of the above measurements a Fast Fourier Transform was applied, producing the variables below.

* fBodyAcc-XYZ  
* fBodyAccJerk-XYZ
* fBodyGyro-XYZ
* fBodyAccMag
* fBodyAccJerkMag
* fBodyGyroMag
* fBodyGyroJerkMag

Each variable has a measurement for the X, Y, and Z axis, denoted by the XYZ next to the variable name above. In the final table each variable will have an X, Y, or Z as the last letter in the variable name to identify which axis is being measured. If there is not an X, Y or Z it is the summary variable across all 3 axes. 

Mean and standard deviation were captured for the variables above. In the final table each variable name will include either mean or std to identify the statistic applied.
